<a href="https://colab.research.google.com/github/tejas928/Machine-Learning-/blob/main/DiabetesPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

diabetes_dataset= pd.read_csv('diabetes_prediction_dataset.csv')
diabetes_dataset.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [2]:
diabetes_dataset.shapeg

(100000, 9)

In [3]:
diabetes_dataset.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [4]:
diabetes_dataset.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [5]:
diabetes_dataset['diabetes'].value_counts()
diabetes_dataset['smoking_history'].value_counts()

smoking_history
No Info        35816
never          35095
former          9352
current         9286
not current     6447
ever            4004
Name: count, dtype: int64

In [ ]:
Separating the labels X and y

In [6]:
X = diabetes_dataset.drop(['diabetes'], axis=1)
y = diabetes_dataset['diabetes']

print(X)

       gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19
1      Female  54.0             0              0         No Info  27.32
2        Male  28.0             0              0           never  27.32
3      Female  36.0             0              0         current  23.45
4        Male  76.0             1              1         current  20.14
...       ...   ...           ...            ...             ...    ...
99995  Female  80.0             0              0         No Info  27.32
99996  Female   2.0             0              0         No Info  17.37
99997    Male  66.0             0              0          former  27.83
99998  Female  24.0             0              0           never  35.42
99999  Female  57.0             0              0         current  22.43

       HbA1c_level  blood_glucose_level
0              6.6                  140
1              6.6                   80
2              5.7                  158
3              5.0                  155
4              4.8                  155
...            ...                  ...
99995          6.2                   90
99996          6.5                  100
99997          5.7                  155
99998          4.0                  100
99999          6.6                   90

[100000 rows x 8 columns]

In [7]:

print(y)

0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    0
Name: diabetes, Length: 100000, dtype: int64

In [8]:
X['smoking_history'].value_counts()

smoking_history
No Info        35816
never          35095
former          9352
current         9286
not current     6447
ever            4004
Name: count, dtype: int64

In [ ]:
Label Encoding for Gender and Smoking_history
0 --> Female 1-->  Male

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['gender'] = le.fit_transform(X['gender'])
X['smoking_history'] = X['smoking_history'].replace({'not current':'former'})

X['smoking_history'] = le.fit_transform(X['smoking_history'])

print(X)

       gender   age  hypertension  heart_disease  smoking_history    bmi  \
0           0  80.0             0              1                4  25.19
1           0  54.0             0              0                0  27.32
2           1  28.0             0              0                4  27.32
3           0  36.0             0              0                1  23.45
4           1  76.0             1              1                1  20.14
...       ...   ...           ...            ...              ...    ...
99995       0  80.0             0              0                0  27.32
99996       0   2.0             0              0                0  17.37
99997       1  66.0             0              0                3  27.83
99998       0  24.0             0              0                4  35.42
99999       0  57.0             0              0                1  22.43

       HbA1c_level  blood_glucose_level
0              6.6                  140
1              6.6                   80
2              5.7                  158
3              5.0                  155
4              4.8                  155
...            ...                  ...
99995          6.2                   90
99996          6.5                  100
99997          5.7                  155
99998          4.0                  100
99999          6.6                   90

[100000 rows x 8 columns]

In [ ]:
Data Standarization

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(X)

array([[-8.41046744e-01,  1.69270354e+00, -2.84439447e-01, ...,
        -3.21055792e-01,  1.00170572e+00,  4.77042159e-02],
       [-8.41046744e-01,  5.38006427e-01, -2.84439447e-01, ...,
        -1.15583678e-04,  1.00170572e+00, -1.42620999e+00],
       [ 1.18723364e+00, -6.16690686e-01, -2.84439447e-01, ...,
        -1.15583678e-04,  1.61108022e-01,  4.89878478e-01],
       ...,
       [ 1.18723364e+00,  1.07094356e+00, -2.84439447e-01, ...,
         7.67292549e-02,  1.61108022e-01,  4.16182767e-01],
       [-8.41046744e-01, -7.94336396e-01, -2.84439447e-01, ...,
         1.22036126e+00, -1.42668764e+00, -9.34905254e-01],
       [-8.41046744e-01,  6.71240710e-01, -2.84439447e-01, ...,
        -7.36921977e-01,  1.00170572e+00, -1.18055762e+00]])

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 1)
print(X_train)
print(X_test)

       gender   age  hypertension  heart_disease  smoking_history    bmi  \
78689       0  48.0             0              0                4  36.26
76423       1  50.0             0              0                4  30.68
86945       0  63.0             0              0                4  38.19
57427       0  36.0             0              0                0  34.55
34616       1  39.0             0              0                4  33.55
...       ...   ...           ...            ...              ...    ...
50057       0  36.0             0              0                4  27.32
98047       0  18.0             0              0                4  19.02
5192        1  80.0             1              0                3  28.36
77708       0  51.0             1              0                3  57.51
98539       0  79.0             0              0                4  27.32

       HbA1c_level  blood_glucose_level
78689          4.0                  130
76423          5.8                  155
86945          3.5                  200
57427          4.0                   90
34616          5.8                  200
...            ...                  ...
50057          5.8                  158
98047          3.5                  126
5192           5.8                   90
77708          6.2                  126
98539          6.0                   90

[80000 rows x 8 columns]
       gender   age  hypertension  heart_disease  smoking_history    bmi  \
43660       0  73.0             0              0                0  26.62
87278       0  35.0             0              0                4  27.32
14317       1  38.0             0              0                0  27.32
81932       0  75.0             0              0                0  31.11
95321       0  51.0             0              0                4  39.57
...       ...   ...           ...            ...              ...    ...
73441       0  19.0             0              0                4  28.27
1341        1   4.0             0              0                4  27.32
71987       0  50.0             1              0                4  24.64
26910       1  30.0             0              0                4  21.53
24890       0  71.0             0              0                0  27.32

       HbA1c_level  blood_glucose_level
43660          5.0                  155
87278          4.5                  130
14317          6.2                  130
81932          6.2                  159
95321          6.2                  240
...            ...                  ...
73441          5.0                  159
1341           5.0                  145
71987          4.8                  145
26910          6.6                  158
24890          4.8                   85

[20000 rows x 8 columns]

In [ ]:
Training the Model

In [17]:
from xgboost import XGBClassifier
xgb_model = XGBClassifier(ojective='binary:logistic', n_estimators=100, random_state=42)
xgb_model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [14:49:00] WARNING: /workspace/src/learner.cc:790:
Parameters: { "ojective" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
Testing the Model Accuracy Score

In [21]:
from sklearn.metrics import accuracy_score
y_pred = xgb_model.predict(X_test)
score = accuracy_score(y_test, y_pred)
score

0.9717

In [23]:
X.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level
0,0,80.0,0,1,4,25.19,6.6,140
1,0,54.0,0,0,0,27.32,6.6,80
2,1,28.0,0,0,4,27.32,5.7,158
3,0,36.0,0,0,1,23.45,5.0,155
4,1,76.0,1,1,1,20.14,4.8,155

Model Prediction

In [32]:

input_data = (0, 80.0 ,0, 1 ,3 ,25.19 ,6.6 ,140)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)
std_data = scaler.transform(input_data_reshaped)


prediction = xgb_model.predict(std_data)

print(prediction)

if(prediction == 0):
    print('The person is not Diabetic')
else:
    print('The person is Diabetic')

[0]
The person is not Diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(